### ISSUE TITLE
Clear facets cache button does nothing

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-hubs#113]
Clear facets cache button does nothing  - on admin page

**Comment by nickdos** [comment]
Fixed last year.

**Comment by djtfmartin** [comment]
This is still an issue. The clear facets button does nothing, while the clear all works.

**Comment by nickdos** [comment]
How did you test this? I'm not sure how to reproduce the issue manually?

**Comment by djtfmartin** [comment]
restart tomcat thats running generic-hubs (or other).
try and clear cache

**Comment by nickdos** [comment]
Just did some testing and it is clearing the cache for the ehcache'ed service calls as well as the grouped facets. So I'm not sure what the problem is. I put logging both inside the methods and outside testing for the values being cleared and its all working as it should - without clearing cache values are stored and code in methods is not called. After cleating caches, the values are lost and code is called and new values are loaded. Maybe the issue is upline and its simple reloading bad data or can't make a connection at the time the cache is reloaded?

**Comment by nickdos** [comment]
@djtfmartin is this still a problem?
